version: "3.7"

services:
  database:
    container_name: qrcodereader-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3307:3306

  php:
    container_name: qrcodereader-php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html/
    restart: always
    # user: 1000:1000
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - database
    links:
      - database      